webserver/mywebsite/mywebsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('quotesvote/', include('quotesvote.urls')),
    path('admin/', admin.site.urls),
]

webserver/mywebsite/quotesvote/urls.py
from django.urls import path

from . import views


app_name = 'quotesvote'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:quote_id>/', views.quote, name='quote'),
    # ex: /polls/5/results/
    path('<int:quote_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:quote_id>/vote/', views.vote, name='vote'),
]

webserver/mywebsite/quotesvote/models.py
import datetime
from django.db import models
from django.utils import timezone


class Quote(models.Model):
    #quote = models.Manager()
    quote_text = models.CharField(max_length=1000)
    #quote_by = tähän

    def __str__(self):
        return self.quote_text


    def quote_by(self):
        pass


class Vote(models.Model):
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE)
    vote_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.vote_text

webserver/mywebsite/quotesvote/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import Http404
from .models import Quote, Vote


def index(request):
    latest_quote_list = Quote.objects.all()
    context = {'latest_quote_list': latest_quote_list}
    return render(request, 'quotesvote/index.html', context)


def quote(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quotesvote/quote.html', {'quote': quote})


def results(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quotesvote/results.html', {'quote': quote})



def vote(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    try:
        selected_choice = quote.vote_set.get(pk=request.POST['vote'])
    except (KeyError, Vote.DoesNotExist):
        # Redisplay the quote voting form.
        return render(request, 'quotesvote/quote.html', {
            'quote': quote,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('quotesvote:results', args=(quote.id,)))

webserver/mywebsite/quotesvote/templates/quotesvote/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Quotes app</title>
  </head>
  <body>
    <p>This is my quotesvote. You can vote for your favorite quotes.</p>
    {% if latest_quote_list %}
    <ul>
    {% for quote in latest_quote_list %}
        <li><a href="{% url 'quotesvote:quote' quote.id %}">{{ quote.quote_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No quotes are avaidable.</p>
{% endif %}
  </body>
</html>

webserver/mywebsite/quotesvote/templates/quotesvote/quote.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Quotesvote app</title>
  </head>
  <body>
    <p>Quote: </p>
      <h1>{{ quote.quote_text }}</h1>
      
      {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      
      <form action="{% url 'quotesvote:vote' quote.id %}" method="post">
      {% csrf_token %}
      {% for vote in quote.vote_set.all %}
          <input type="radio" name="vote" id="vote{{ forloop.counter }}" value="      {{ vote.id }}">     
          <label for="vote{{ forloop.counter }}">{{ vote.vote_text }}</label><br>    
      {% endfor %}
      <input type="submit" value="Vote">
      </form>
      </ul>
      <form action="{% url 'quotesvote:index' %}" method="post">
      {% csrf_token %}
          <input type="submit" value="Go to mainpage" />
      </form>
  </body>
</html>

webserver/mywebsite/quotesvote/templates/quotesvote/results.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Quotesvote app</title>
  </head>
  <body>
    <p>This is results</p>
<h1>{{ quote.quote_text }}</h1>

<ul>
{% for vote in quote.vote_set.all %}
    <li>{{ vote.vote_text }} -- {{ vote.votes }} vote{{ vote.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'quotesvote:quote' quote.id %}">Vote again?</a>
  </body>
        <form action="{% url 'quotesvote:index' %}" method="post">
      {% csrf_token %}
          <input type="submit" value="Go to mainpage" />
</html>